### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/python-p3-regex-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204253?module_item_id=468003

### Concern

I really don't think this is a well written lab. I hope the curriculum team will dive into this section a little more carefully. It has never been well taught in our curriculum and this new python roll out represents an opportunity to do something different. Happy to talk more about this with the writers.

### Suggested Changes

Perhaps make the context a real life situation where regex would be used. It would make it more comprehensible and less arbitrary.

**Comment by professor-ben** [comment]
I've modified this lab to be a "Bonus" and created a new lab, visible here: https://github.com/learn-co-curriculum/python-p3-regex-validations-lab

This should provide more real-world context for regular expressions. We will continue to work on this module.

Thanks for your feedback,
Ben
